/**
 * Composable Storefront が `CmsConfig.cmsComponents` に登録している全CMSコンポーネント型(228件)。
 * spartacus リポジトリ(2211.15.1 相当)を機械走査して抽出したもの。
 * 分類と解説は docs/component-catalog.md を参照。
 *
 * 用途: 各CMSコンポーネントは `[cxOutlet]="component.flexType"` で描画されるため
 * (core-libs/storefront/cms-structure/page/slot/page-slot.component.html)、
 * この型名を outlet id として provideOutlet すれば「全コンポーネント一括カスタマイズ」ができる。
 */
export const ALL_CMS_COMPONENT_TYPES: string[] = [
  // --- コンテンツ系(storefront/content) ---
  'SimpleBannerComponent',
  'BannerComponent',
  'SimpleResponsiveBannerComponent',
  'RotatingImagesComponent',
  'CMSParagraphComponent',
  'CMSTabParagraphComponent',
  'CMSTabParagraphContainer',
  'CMSLinkComponent',
  'VideoComponent',
  'PDFDocumentComponent',
  // --- ナビゲーション系(storefront/navigation) ---
  'NavigationComponent',
  'CategoryNavigationComponent',
  'FooterNavigationComponent',
  'BreadcrumbComponent',
  'SearchBoxComponent',
  'PageTitleComponent',
  'ScrollToTopComponent',
  'HamburgerMenuComponent',
  // --- 商品系(storefront/product) ---
  'ProductIntroComponent',
  'ProductSummaryComponent',
  'ProductImagesComponent',
  'ProductDetailsTabComponent',
  'ProductSpecsTabComponent',
  'ProductReviewsTabComponent',
  'ProductCarouselComponent',
  'ProductReferencesComponent',
  'CMSProductListComponent',
  'ProductGridComponent',
  'SearchResultsListComponent',
  'ProductRefinementComponent',
  'StockNotificationComponent',
  // --- サイト共通(storefront/misc) ---
  'CMSSiteContextComponent',
  'LanguageCurrencyComponent',
  'SiteThemeSwitcherComponent',
  'AnonymousConsentManagementBannerComponent',
  'AnonymousConsentOpenDialogComponent',
  // --- My Account 汎用(storefront/myaccount) ---
  'AccountPaymentDetailsComponent',
  'ConsentManagementComponent',
  'NotificationPreferenceComponent',
  'MyCouponsComponent',
  'CouponClaimComponent',
  'ClaimDialogComponent',
  'MyInterestsComponent',
  'MyAccountSideNavigationComponent',
  // --- user(account / profile) ---
  'LoginComponent',
  'ReturningCustomerLoginComponent',
  'ReturningCustomerOTPLoginComponent',
  'VerifyOTPTokenComponent',
  'ReturningCustomerRegisterComponent',
  'ReturningOrganizationUserRegisterComponent',
  'MyAccountViewUserComponent',
  'RegisterCustomerComponent',
  'RegisterCustomerWithOTPComponent',
  'VerifyOTPForRegistrationComponent',
  'ForgotPasswordComponent',
  'ResetPasswordComponent',
  'UpdateEmailComponent',
  'UpdatePasswordComponent',
  'UpdateProfileComponent',
  'CloseAccountComponent',
  'AccountAddressBookComponent',
  // --- cart(base) ---
  'CartComponent',
  'CartTotalsComponent',
  'CartProceedToCheckoutComponent',
  'CartApplyCouponComponent',
  'MiniCartComponent',
  'ProductAddToCartComponent',
  'SaveForLaterComponent',
  'ClearCartComponent',
  // --- cart(saved-cart / quick-order / import-export / wish-list) ---
  'AddToSavedCartsComponent',
  'AccountSavedCartHistoryComponent',
  'SavedCartDetailsActionComponent',
  'SavedCartDetailsItemsComponent',
  'SavedCartDetailsOverviewComponent',
  'QuickOrderComponent',
  'CartQuickOrderFormComponent',
  'ImportOrderEntriesComponent',
  'ExportOrderEntriesComponent',
  'ImportExportOrderEntriesComponent',
  'AddToWishListComponent',
  'WishListComponent',
  // --- checkout(base / b2b / scheduled-replenishment) ---
  'CheckoutOrchestrator',
  'CheckoutProgress',
  'CheckoutProgressMobileTop',
  'CheckoutProgressMobileBottom',
  'CheckoutDeliveryAddress',
  'CheckoutDeliveryMode',
  'CheckoutPaymentDetails',
  'CheckoutReviewOrder',
  'CheckoutReviewOverview',
  'CheckoutReviewShipping',
  'CheckoutReviewPayment',
  'CheckoutPlaceOrder',
  'CheckoutOrderSummary',
  'GuestCheckoutLoginComponent',
  'CheckoutPaymentType',
  'CheckoutCostCenterComponent',
  'CheckoutScheduleReplenishmentOrder',
  // --- order ---
  'AccountOrderHistoryComponent',
  'AccountOrderDetailsItemsComponent',
  'AccountOrderDetailsTotalsComponent',
  'AccountOrderDetailsOverviewComponent',
  'AccountOrderDetailsSimpleOverviewComponent',
  'AccountOrderDetailsActionsComponent',
  'AccountOrderDetailsGroupedItemsComponent',
  'AccountOrderDetailsReorderComponent',
  'AccountOrderAttachmentsComponent',
  'OrderConfirmationThankMessageComponent',
  'OrderConfirmationOverviewComponent',
  'OrderConfirmationItemsComponent',
  'OrderConfirmationTotalsComponent',
  'OrderConfirmationShippingComponent',
  'OrderConfirmationBillingComponent',
  'CancelOrderComponent',
  'CancelOrderConfirmationComponent',
  'ReturnOrderComponent',
  'ReturnOrderConfirmationComponent',
  'OrderReturnRequestListComponent',
  'ReturnRequestOverviewComponent',
  'ReturnRequestItemsComponent',
  'ReturnRequestTotalsComponent',
  'AccountReplenishmentHistoryComponent',
  'ReplenishmentDetailActionsComponent',
  'ReplenishmentDetailItemsComponent',
  'ReplenishmentDetailOrderHistoryComponent',
  'ReplenishmentDetailShippingComponent',
  'ReplenishmentDetailTotalsComponent',
  'ReplenishmentConfirmationItemsComponent',
  'ReplenishmentConfirmationMessageComponent',
  'ReplenishmentConfirmationOverviewComponent',
  'ReplenishmentConfirmationTotalsComponent',
  'MyAccountViewOrderComponent',
  'AccountOrderDocumentFlowComponent',
  // --- pdf-invoices ---
  'AccountOrderDetailsPDFInvoicesComponent',
  // --- organization(administration / order-approval / unit-order / account-summary / user-registration) ---
  'ManageBudgetsListComponent',
  'ManageCostCentersListComponent',
  'ManageUnitsListComponent',
  'ManageUsersListComponent',
  'ManageUserGroupsListComponent',
  'ManagePermissionsListComponent',
  'ManageAccountSummaryListComponent',
  'AccountSummaryHeaderComponent',
  'AccountSummaryDocumentComponent',
  'OrderApprovalListComponent',
  'OrderApprovalDetailApprovalDetailsComponent',
  'OrderApprovalDetailFormComponent',
  'OrderApprovalDetailItemsComponent',
  'OrderApprovalDetailShippingComponent',
  'OrderApprovalDetailTotalsComponent',
  'AccountOrderDetailsApprovalDetailsComponent',
  'UnitLevelOrderHistoryComponent',
  'UnitLevelOrderDetailsItemsComponent',
  'UnitLevelOrderDetailsOverviewComponent',
  'UnitLevelOrderDetailsTotalsComponent',
  'OrganizationUserRegistrationComponent',
  'RegisterB2BCustomerWithOTPComponent',
  'VerifyOTPForB2BRegistrationComponent',
  // --- quote ---
  'AccountMyQuotesComponent',
  'QuoteRequestComponent',
  'QuoteHeaderOverviewComponent',
  'QuoteItemsComponent',
  'QuoteSummaryComponent',
  'QuoteCommentsComponent',
  'QuoteLinksComponent',
  'QuoteCartGuardComponent',
  // --- customer-ticketing ---
  'SupportTicketHistoryComponent',
  'SupportTicketDetailsComponent',
  'SupportTicketUpdateComponent',
  'SupportTicketCloseComponent',
  'SupportTicketReopenComponent',
  'MyAccountViewRequestsComponent',
  // --- storefinder / pickup-in-store ---
  'StoreFinderComponent',
  'PickupInStoreDeliveryModeComponent',
  'CheckoutReviewPickup',
  'OrderConfirmationPickUpComponent',
  'MyPreferredStoreComponent',
  // --- product(variants / multi-dimensional / bulk-pricing / future-stock) ---
  'ProductVariantSelectorComponent',
  'ProductMultiDimensionalSelectorComponent',
  'BulkPricingTableComponent',
  'FutureStockComponent',
  // --- product-configurator(common / rulebased / textfield) ---
  'ConfigureProductComponent',
  'ConfiguratorForm',
  'ConfiguratorMenu',
  'ConfiguratorGroupTitle',
  'ConfiguratorPrevNext',
  'ConfiguratorPriceSummary',
  'ConfiguratorAddToCartButton',
  'ConfiguratorTabBar',
  'ConfiguratorUpdateMessage',
  'ConfiguratorProductTitle',
  'ConfiguratorExitButton',
  'ConfiguratorOverviewBanner',
  'ConfiguratorOverviewFilterButton',
  'ConfiguratorOverviewForm',
  'ConfiguratorOverviewSidebar',
  'ConfiguratorVariantCarousel',
  'CpqConfiguratorConflictAndErrorMessagesComponent',
  'TextfieldConfigurationForm',
  // --- qualtrics / subscription-billing ---
  'QualtricsComponent',
  'QualtricsEmbeddedFeedbackComponent',
  'SubscriptionDetailsComponent',
  'SubscriptionHistoryComponent',
  'SubscriptionBillDetailsComponent',
  'SubscriptionBillsHistoryComponent',
  'SubscriptionProductPriceComponent',
  // --- integration-libs(cdc / cds / opf / punchout / s4-service / epd-visualization) ---
  'GigyaRaasComponent',
  'MerchandisingCarouselComponent',
  'ProfileTagComponent',
  'OpfB2bCheckoutPaymentAndReview',
  'OpfCheckoutDeliveryAddress',
  'OpfCheckoutEmailUpdateComponent',
  'OpfCheckoutPaymentAndReview',
  'OpfCheckoutPaymentType',
  'OpfCheckoutReview',
  'OpfCtaQuickBuyButtons',
  'OpfCtaScriptsComponent',
  'OpfQuickBuyButtonsComponent',
  'PunchoutButtonsComponent',
  'PunchoutCloseSessionComponent',
  'PunchoutErrorComponent',
  'PunchoutInspectCartComponent',
  'PunchoutRequisitionComponent',
  'PunchoutSessionComponent',
  'CancelServiceOrder',
  'CancelServiceOrderHeadline',
  'RescheduleServiceOrder',
  'CheckoutServiceDetails',
  'VisualPickingTabComponent',
];
